# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Distiller
tagline:          build and deploy ios apps faster
description:      Hosted Continuous Integration for iOS
url:              http://distiller.io

author:
  name:           The Distiller Team
  url:            http://distiller.io

paginate:         1

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/distiller/blog.distiller.io

authors:
  jim:
    name: Jim Rose
    display_name: Jim Rose
  rob:
    name: Rob Zuber
    display_name: Rob Zuber
  travis:
    name: Travis Vachon
    display_name: Travis Vachon
  team:
    name: The Distiller Team
    display_name: The Distiller Team
